package com.prodian.rsgirms.dashboard.model.response;
import java.util.List;

import com.prodian.rsgirms.userapp.model.User;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class R12CubeResponse {

	
	private double gepOd;
    private double gepTp;
    private double nepOd;
    private double nepTp;
    private double discountGepOd;
    private double discountNepOd;
    private double gepDepOd;
    private double gepDepTp;
    private double gepNcbOd;
    private double gepNcbTp;
    private double gepOtherAddonOd;
    private double gepOtherAddonTp;
    private double nepDepOd;
    private double nepDepTp;
    private double nepNcbOd;
    private double nepNcbTp;
    private double nepOtherAddonOd;
    private double nepOtherAddonTp;
    private double earnedPoliciesOd;
    private double earnedPoliciesTp;
    private double addonEarnedPoliciesOd;
    private double addonEarnedPoliciesTp;
    private double gicTpUlr;
    private double gicTpUlrDep;
    private double gicTpUlrNcb;
    private double gicTpUlrOtherAddon;
    private double nicTpUlr;
    private double nicTpUlrDep;
    private double nicTpUlrNcb;
    private double nicTpUlrOtherAddon;
    private double gwpOd;
    private double gwpTp;
    private double nwpOd;
    private double nwpTp;
    private double gwpDepOd;
    private double gwpDepTp;
    private double gwpNcbOd;
    private double gwpNcbTp;
    private double gwpOtherAddonOd;
    private double gwpOtherAddonTp;
    private double nwpDepOd;
    private double nwpDepTp;
    private double nwpNcbOd;
    private double nwpNcbTp;
    private double nwpOtherAddonOd;
    private double nwpOtherAddonTp;
    private double policyCountTp;
    private double policyCountOd;
    private double policyCountOthers;
    private double addonPolicyCountTp;
    private double addonPolicyCountOd;
    private double addonPolicyCountOthers; 
    private double acqCostOd;
    private double acqCostTp;
    private double addonAcqCostOd;
    private double addonAcqCostTp;
    private double catClaimCount;
    private double theftClaimCount;
    private double otherClaimCount;
    private double addonCatCount;
    private double addonTheftCount;
    private double addonOtherCount;
    private double addonClaimCountTp;
    private double catGic;
    private double theftGic;
    private double otherGic;
    private double gicTp;
    private double catNic;
    private double theftNic;
    private double otherNic;
    private double nicTp;
    private double addonCatGic;
    private double addonTheftGic;
    private double addonOtherGic;
    private double addonGicTp;
    private double addonCatNic;
    private double addonTheftNic;
    private double addonOtherNic;
    private double addonNicTp;
    private double estimatedGic;
    private double estimatedCatGic;
    private double estimatedTheftGic;
    private double estimatedOtherGic;
    private double estimatedTpGic;
    private double estimatedAddonGic;
    private double estimatedAddonCatGic;
    private double estimatedAddonTheftGic;
    private double estimatedAddonOtherGic;
    private double estimatedAddonTpGic;
    private double estimatedLossRatio;
    private double estimatedOdLossRatio;
    private double estimatedTpLossRatio;
    private double estimatedTpUlrLossRatio;
    private double estimatedAddonLossRatio;
    private double estimatedAddonOdLossRatio;
    private double estimatedAddonTpLossRatio;
    private double estimatedAddonTpUlrLossRatio;
    private double r12Freq;
    private double r12CatFreq;
    private double r12TheftFreq;
    private double r12OthersFreq;
    private double r12TpFreq;
    private double r12AddonFreq;
    private double r12AddonCatFreq;
    private double r12AddonTheftFreq;
    private double r12AddonOthersFreq;
    private double r12AddonTpFreq;
    private double r12Severity;
    private double r12CatSeverity;
    private double r12TheftSeverity;
    private double r12OthersSeverity;
    private double r12TpSeverity;
    private double r12AddonSeverity;
    private double r12AddonCatSeverity;
    private double r12AddonTheftSeverity;
    private double r12AddonOthersSeverity;
    private double r12AddonTpSeverity;
    private double r12LossRatio;
    private double r12OdLossRatio;
    private double r12TpLossRatio;
    private double r12TpUlrLossRatio;
    private double r12AddonLossRatio;
    private double r12AddonOdLossRatio;
    private double r12AddonTpLossRatio;
    private double r12AddonTpUlrLossRatio;
    private double freq;
    private double catFreq;
    private double theftFreq;
    private double otherFreq;
    private double severity;
    private double catSeverity;
    private double theftSeverity;
    private double otherSeverity;
    private double lossRatio;
    private double odLossRatio;
    private double tpUlrLossRatio;
    private double tpLossRatio;
    
}
