package com.prodian.rsgirms.usermatrix.enums;

public enum DimensionEnum {
	
	ZONE,CLUSTER,STATE,BRANCH,PRODUCT,LOB,BUSINESS_TYPE,CHANNEL,SUBCHANNEL,MAKE,MODEL,
	ADD_ONS,CITY,MODEL_CLASSIFICATION,
	MODEL_GROUP,OA_CODE,OA_NAME,PINCODE,POLICY_CATEGORY,POLICY_TYPE,REGION,T20_LOCATION

}
